[package]
name = "rusty_pals"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
clap = { version = "4.0", features = ["derive", "color"] }
anyhow = "1.0"

[profile.release]
debug = true
