[package]
name = "rusty_pals"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "crypto_core",
  "xor_encrypt",
  "xor_brute",
]

[profile.release]
debug = true

[profile.dev]
opt-level = 2
